### PR TITLE
Change "wants to merge" text when viewing merged PR

### LINKED ISSUE #1027: Merged pull request should use past tense
- Extension version:
- VSCode Version:
- OS: MacOS

Steps to Reproduce:

1. Merge an open pull request
2. View pull request header

screen shot 2019-03-04 at 9 35 03 pm

Compared with GitHub.com:
screen shot 2019-03-05 at 8 26 45 am

Expected result:
meaghanlewis **merged** changes (instead of meaghanlewis **wants to merge**)

### PR DESCRIPTION
**Pull request by smashwilson**
When viewing an unmerged pull request, the header looks like so:

before-merge

When viewing a merged pull request, it now reads as:

after-merged

Fixes #1027.

### CODE REVIEW

File: preview-src/header.tsx [hunk 1]
```diff
@@ -105,4 +106,12 @@ export function getStatus(state: PullRequestStateEnum) {
 	} else {
 		return 'Closed';
 	}
+}
+
+export function getActionText(state: PullRequestStateEnum) {
```
Comment (RMacfarlane) [inline preview-src/header.tsx]: nit: no need to export

Comment (smashwilson) [reply preview-src/header.tsx]: Un-exported 👍
