### PR TITLE
Issue completions not working in SCM input

### LINKED ISSUE #2064: Issue completions not working in SCM input
With the new multi-repo model the SCM input box is handled incorrectly and now issue completions are not presented.

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #2064

### CODE REVIEW

File: src/issues/issueCompletionProvider.ts [hunk 1]
```diff
@@ -54,12 +54,17 @@ export class IssueCompletionProvider implements vscode.CompletionItemProvider {
 		const completionItems: Map<string, vscode.CompletionItem> = new Map();
 		const now = new Date();
 		let repo: PullRequestDefaults | undefined;
+		const uri = (document.languageId === 'scminput') ? getRootUriFromScmInputUri(document.uri) : document.uri;
+		if (!uri) {
+			return [];
+		}
+
```
Comment (RMacfarlane) [inline src/issues/issueCompletionProvider.ts:61]: tslint warning about trailing whitespace

File: src/issues/userCompletionProvider.ts [hunk 2]
```diff
@@ -36,7 +36,12 @@ export class UserCompletionProvider implements vscode.CompletionItemProvider {
 				range = new vscode.Range(position.translate(0, -1), position);
 			}
 		}
-		const uri = document.uri.scheme === NEW_ISSUE_SCHEME ? (extractIssueOriginFromQuery(document.uri) ?? document.uri) : document.uri;
+		const uri = document.uri.scheme === NEW_ISSUE_SCHEME ? (extractIssueOriginFromQuery(document.uri) ?? document.uri) :
+			(document.languageId === 'scminput' ? getRootUriFromScmInputUri(document.uri) : document.uri);
+		if (!uri) {
+			return [];
+		}
+
```
Comment (RMacfarlane) [inline src/issues/userCompletionProvider.ts:44]: tslint warning about trailing whitespace
