### PR TITLE
Better support for merging when in dirty state

### LINKED ISSUE #1405: Handle checkout failure when deleting pull request
- Extension version: 0.12.0

Steps to Reproduce:

1. Check out a pull request
2. Make local changes to the workspace
3. Merge the PR
4. Use "Delete" button from the description page and check all boxes

Delete tries to switch branches and delete the old branch. This silently fails with a "DirtyWorkTree" error from git since there are local changes.

### PR DESCRIPTION
**Pull request by JacksonKearl**
Fixes #1405

Adds:

- When trying to merge with a dirty directory or unpushed changes, user gets a confirmation dialog
- When trying to delete a branch post-merge, if the branch has uncommitted changes, the user gets a confirmation dialog to discard them.

### CODE REVIEW

**Comment by JacksonKearl** [comment]
Fixes https://github.com/microsoft/vscode-pull-request-github/issues/1405

File: src/github/pullRequestOverview.ts [hunk 1]
```diff
@@ -618,19 +618,23 @@ export class PullRequestOverviewPanel {
...
+								if (response === 'Yes') {
+									await vscode.commands.executeCommand('git.cleanAll');
+								} else {
+									return;
+								}
 							}
-
-							await this._pullRequestManager.repository.deleteBranch(branchInfo!.branch, true);
-							resolve();
-						});
```
Comment (JacksonKearl) [inline src/github/pullRequestOverview.ts]: Not sure why this was done with explicit promise construction?

Comment (RMacfarlane) [reply src/github/pullRequestOverview.ts]: a mystery 🤷‍♀
