### PR TITLE
Fixes #2259

### LINKED ISSUE #2259: issueBranchTitle not Working as Expected
No matter what I do I cannot get this pluging to accept and use this formatting in the devcontainer.json (and all other settings.json) **if the branch was previously created with the default format**

"githubIssues.issueBranchTitle": "${user}-issue${issueNumber}",

The branch is always created in the default format. Even if I delete the "bad" branch. Is there metadata for this and how do I delete it?

It seems like once you've created a branch with any name then the new settings are impossible to take effect on a branch that was previously created. It seems like some metadata is stored somewhere? Is that deletable?

### PR DESCRIPTION
**Pull request by burkeholland**
Check to see if new branch name per config is different from what is in state. If so, and branch has been deleted, update branch name to new config calculated value.

### CODE REVIEW

File: src/issues/currentIssue.ts [hunk 1]
```diff
@@ -201,13 +201,19 @@ export class CurrentIssue {
...
+			undefined,
+			await this.getUser(),
+		);
+		if (this._branchName !== branchNameConfig) {
+			const branchExists = await this.branchExists(this._branchName!);
+			if (!branchExists) {
+				this._branchName = branchNameConfig;
+			}
+		}
 		if (!this._branchName) {
```
Comment (alexr00) [inline src/issues/currentIssue.ts:216]: We also need to do this `if` if `this._branchName` changed in the previous block since it includes branch name validation.

**Review by alexr00 — CHANGES_REQUESTED** [review]
Just one change needed I think! I still think we should also offer to "move to"/"rename" the old branch if it exists, but that can be a separate PR since this is a good change regardless.

File: src/issues/currentIssue.ts (hunk 1 above)
Comment (alexr00) [reply src/issues/currentIssue.ts:216]: @burkeholland this is the only change I see that is needed before merging!

Comment (alexr00) [reply src/issues/currentIssue.ts:216]: I was thinking something like this, since we still needed to validate the branch name:

https://github.com/microsoft/vscode-pull-request-github/pull/2909/files#diff-e0d767b263cbb178ca6cf7902e1934d49d08810ea2f4c26d97d23b98e5643210R231-R236

**Review by alexr00 — APPROVED** [review]
I pushed the change, it all looks good. Thank you!
