### PR TITLE
Batch mark/unmark files as viewed

### LINKED ISSUE #4520: batch mark/unmark file as viewed silently fails for large file sets
- Extension version: 0.58.1
- VSCode Version: 1.75.1
- OS: macOS Ventura 13.1

Steps to Reproduce:

1. Open a pull request containing 300+ file changes in a single folder
2. Click the checkbox on the folder to mark all 300+ files as viewed
- There will be error logs in the console and if you reload the editor or view the PR on github.com you'll see that not all files were marked as read

I suggest adding support for marking/unmarking a set of files as viewed so that's its a single API call instead of what I think is being done through lots of tiny calls.

### PR DESCRIPTION
**Pull request by joshuaobrien**
## Context
Previously, when marking/unmarking a folder as viewed, a request was sent for every single file. This PR ensures that only one request is sent when marking/unmarking a folder as viewed.

Fixes #4520

## Before
https://user-images.githubusercontent.com/7654793/229513098-670ad525-4e05-44ff-bd3e-10cab4781113.mp4

## After
https://user-images.githubusercontent.com/7654793/229513184-fab21149-52b2-4b16-b23b-4f4a3b483383.mp4

### CODE REVIEW

File: src/github/pullRequestModel.ts [hunk 1]
```diff
@@ -1566,42 +1567,56 @@ export class PullRequestModel extends IssueModel<PullRequest> implements IPullRe
...
+			);
+
+		const mutation = gql`mutation BatchMarkFileAsViewedInline {
+			${filenames.map((path) =>
+				`${path.split('/').join('')}: markFileAsViewed(
+					input: {path: "${path}", pullRequestId: "${pullRequestId}"}
+				) { clientMutationId }
+				`
+			)}
+		}`;
```
Comment (joshuaobrien) [inline src/github/pullRequestModel.ts:1588]: Wasn't too sure about inlining these, but given that they are dynamic it seemed like the way to go

Comment (alexr00) [reply src/github/pullRequestModel.ts:1641]: I'm not a fan of this inlining. Is it possible to do without the inlining and instead have a new query in `queries.gql`?

File: src/view/treeNodes/directoryTreeNode.ts [hunk 2]
```diff
@@ -109,22 +110,40 @@ export class DirectoryTreeNode extends TreeNode implements vscode.TreeItem2 {
...
 
 		if (this.parent instanceof TreeNode && !this.parent.updateParentCheckbox()) {
 			this.refresh(this);
 		}
 	}
 
+	// recursively gathers the paths of all files in this directory and the directories below
+	private gatherPaths() {
+		const subDirectories = this.children.filter((child): child is DirectoryTreeNode => child instanceof DirectoryTreeNode);
+		const paths = this.children.filter((child): child is RemoteFileChangeNode | InMemFileChangeNode | GitFileChangeNode => !(child instanceof DirectoryTreeNode)).map(child => child.fileName);
```
Comment (alexr00) [inline src/view/treeNodes/directoryTreeNode.ts:142]: Here we're now going through all children (of which there could be many) 2x, when we could instead iterate through once and add each child to `subDirectories` or `paths` as appropriate.

File: src/view/prsTreeDataProvider.ts [hunk 3]
```diff
@@ -104,7 +104,7 @@ export class PullRequestsTreeDataProvider implements vscode.TreeDataProvider<Tre
 			checkboxUpdates.items.forEach(checkboxUpdate => {
 				const node = checkboxUpdate[0];
 				const newState = checkboxUpdate[1];
-				node.updateCheckbox(newState);
+				node.updateCheckbox(newState, false);
```
Comment (alexr00) [inline src/view/prsTreeDataProvider.ts:107]: Why is the second parameter `false` here?

File: src/view/treeNodes/fileChangeNode.ts [hunk 4]
```diff
@@ -170,33 +170,34 @@ export class FileChangeNode extends TreeNode implements vscode.TreeItem2 {
...
 
-		async function markFile(node: FileChangeNode) {
-			if (newState === vscode.TreeItemCheckboxState.Checked) {
-				await node.markFileAsViewed();
-			}
-			else {
-				await node.unmarkFileAsViewed();
-			}
+		if (performMutation) {
+			await this.markFile(this, viewed);
```
Comment (alexr00) [inline src/view/treeNodes/fileChangeNode.ts:195]: It would be clearer if instead of passing in `this` to `markFile` it instead just accessed `this` in `markFile`.

Comment (alexr00) [reply src/view/treeNodes/fileChangeNode.ts:195]: Also, IIRC awaiting `markFile` here caused the tree to get stuck refreshing. Is that no longer a problem?

**Review by alexr00 — CHANGES_REQUESTED** [review]
Thank you for the PR! It looks like its heading in a very good direction! I have a few questions/comments.

File: src/view/treeNodes/fileChangeNode.ts (hunk 4 above)
Comment (joshuaobrien) [reply src/view/treeNodes/fileChangeNode.ts:195]: Oh, yeah. There's no need to `await` here. I'll refactor 👍

**Comment by joshuaobrien** [comment]
> I'm not a fan of this inlining. Is it possible to do without the inlining and instead have a new query in queries.gql

I spent a bit of time investigating this before raising this PR, but I couldn't find a way to do it. That said, I've never used graphql before outside of this project so I'm sure I'm missing something. I'll take another look this evening!

**Review by alexr00 — CHANGES_REQUESTED** [review]
Thanks for the updates! In the future, it would make reviewing PRs much easier/faster for me if you don't force push your branch. It's hard to tell which files have changed since my last review after a force push.

I tested this out and it doesn't seem to work. I get this error:

```
stack trace: GraphQLError: Syntax Error: Cannot parse the unexpected character ".".
    at syntaxError (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\error\syntaxError.js:15:1)
    at readToken (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\lexer.js:360:1)
    at Lexer.lookahead (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\lexer.js:75:1)
    at Lexer.advance (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\lexer.js:58:1)
    at Parser.expectToken (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:1408:1)
    at Parser.parseName (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:98:1)
    at Parser.parseField (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:295:1)
    at Parser.parseSelection (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:284:1)
    at Parser.many (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:1523:1)
    at Parser.parseSelectionSet (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:271:1)
    at Parser.parseOperationDefinition (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:199:1)
    at Parser.parseDefinition (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:137:1)
    at Parser.many (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:1523:1)
    at Parser.parseDocument (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:115:1)
    at parse (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:31:1)
    at parseDocument (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql-tag\src\index.js:129:1)
    at gql (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql-tag\src\index.js:170:1)
    at _PullRequestModel.markFilesAsViewed (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\src\github\pullRequestModel.ts:1629:23)
extensionHostProcess.js:105
unhandledRejection {"message":"Syntax Error: Cannot parse the unexpected character \".\".","locations":[{"line":2,"column":25}]}
extensionHostProcess.js:105
rejected promise not handled within 1 second: Syntax Error: Cannot parse the unexpected character ".".
```

**Comment by joshuaobrien** [comment]
> Thanks for the updates! In the future, it would make reviewing PRs much easier/faster for me if you don't force push your branch. It's hard to tell which files have changed since my last review after a force push.
> 
> I tested this out and it doesn't seem to work. I get this error:
> 
> ```
> stack trace: GraphQLError: Syntax Error: Cannot parse the unexpected character ".".
>     at syntaxError (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\error\syntaxError.js:15:1)
>     at readToken (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\lexer.js:360:1)
>     at Lexer.lookahead (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\lexer.js:75:1)
>     at Lexer.advance (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\lexer.js:58:1)
>     at Parser.expectToken (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:1408:1)
>     at Parser.parseName (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:98:1)
>     at Parser.parseField (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:295:1)
>     at Parser.parseSelection (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:284:1)
>     at Parser.many (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:1523:1)
>     at Parser.parseSelectionSet (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:271:1)
>     at Parser.parseOperationDefinition (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:199:1)
>     at Parser.parseDefinition (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:137:1)
>     at Parser.many (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:1523:1)
>     at Parser.parseDocument (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:115:1)
>     at parse (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql\language\parser.js:31:1)
>     at parseDocument (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql-tag\src\index.js:129:1)
>     at gql (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\node_modules\graphql-tag\src\index.js:170:1)
>     at _PullRequestModel.markFilesAsViewed (d:\repos\Microsoft\vscode-pull-request-github-2\dist\webpack:\vscode-pull-request-github\src\github\pullRequestModel.ts:1629:23)
> extensionHostProcess.js:105
> unhandledRejection {"message":"Syntax Error: Cannot parse the unexpected character \".\".","locations":[{"line":2,"column":25}]}
> extensionHostProcess.js:105
> rejected promise not handled within 1 second: Syntax Error: Cannot parse the unexpected character ".".
> ```

Huh okay. I'll see if I can reproduce that locally. I'll push up a fix if I can.

**Comment by joshuaobrien** [comment]
This completely dropped off my radar. I'll fix it up and send it back for review soon.

Given how long it's been, I rebased my branch rather than have a massive merge commit. This required a force push, sorry. I won't force push for any further changes.

**Comment by alexr00** [comment]
@joshuaobrien very good timing, thanks for reviving the change! We are doing issue/pr clean up in December and your PR is at the top of my list of my list.

File: src/github/pullRequestModel.ts [hunk 5]
```diff
@@ -1751,42 +1752,44 @@ export class PullRequestModel extends IssueModel<PullRequest> implements IPullRe
...
+		for (let i = 0; i < allFilenames.length; i += this.BATCH_SIZE) {
+			const batch = allFilenames.slice(i, i + this.BATCH_SIZE);
+			const mutation = gql`mutation BatchUnmarkFileAsViewedInline {
+				${batch.map((filename, i) =>
+					`alias${i}: ${mutationName}(
+						input: {path: "${filename}", pullRequestId: "${pullRequestId}"}
+					) { clientMutationId }
+					`
+				)}
+			}`;
```
Comment (joshuaobrien) [inline src/github/pullRequestModel.ts:1784]: Related comment: https://github.com/microsoft/vscode-pull-request-github/pull/4700#discussion_r1165606886

Unfortunately I couldn't find a way around this inlining. It seems when we're creating a query dynamically, this is how it needs to be. Very happy to be shown a different way though; inlining doesn't feel great.

File: src/view/treeNodes/treeNode.ts [hunk 6]
```diff
@@ -66,6 +67,36 @@ export abstract class TreeNode implements vscode.Disposable {
 
 	updateFromCheckboxChanged(_newState: vscode.TreeItemCheckboxState): void { }
 
+	static processCheckboxUpdates(checkboxUpdates: vscode.TreeCheckboxChangeEvent<TreeNode>) {
```
Comment (joshuaobrien) [inline src/view/treeNodes/treeNode.ts:70]: Probably not the ideal place for this. I wanted somewhere easily accessible for both `prChangesTreeDataProvider.ts` and `prsTreeDataProvider.ts`. Where would you recommend I put it?

File: src/view/treeNodes/treeNode.ts [hunk 7]
```diff
@@ -66,6 +67,36 @@ export abstract class TreeNode implements vscode.Disposable {
...
+				} else {
+					uncheckedNodes.push(node);
+				}
+			}
+
+			node.updateFromCheckboxChanged(newState);
+		});
+
+		if (checkedNodes.length > 0) {
+			const prModel = checkedNodes[0].pullRequest;
```
Comment (joshuaobrien) [inline src/view/treeNodes/treeNode.ts:90]: Is it safe to assume that all nodes will be associated with the same PR?

File: src/github/pullRequestModel.ts [hunk 8]
```diff
@@ -1751,42 +1752,58 @@ export class PullRequestModel extends IssueModel<PullRequest> implements IPullRe
...
+			? 'markFileAsViewed'
+			: 'unmarkFileAsViewed';
+
+		// We only ever send 100 mutations at once. Any more than this and
+		// we risk a timeout from GitHub.
+		for (let i = 0; i < allFilenames.length; i += this.BATCH_SIZE) {
+			const batch = allFilenames.slice(i, i + this.BATCH_SIZE);
+			// See below for an example of what a mutation produced by this
+			// will look like
+			const mutation = gql`mutation Batch${mutationName}{
```
Comment (joshuaobrien) [inline src/github/pullRequestModel.ts:1778]: Related comment: https://github.com/microsoft/vscode-pull-request-github/pull/4700#discussion_r1165606886

Unfortunately I couldn't find a way around this inlining. It seems when we're creating a query dynamically, this is how it needs to be. Very happy to be shown a different way though; inlining doesn't feel great.

File: src/view/treeNodes/treeNode.ts (hunk 6 above)
Comment (alexr00) [reply src/view/treeNodes/treeNode.ts]: There isn't an existing place that this fits nicely. Let's put it in a new `treeUtils.ts` file next to `treeNode.ts`.

File: src/github/pullRequestModel.ts (hunk 8 above)
Comment (alexr00) [reply src/github/pullRequestModel.ts:1778]: The benefit we get from batching is worth the inlining. Thanks for checking

**Review by alexr00 — APPROVED** [review]
Thanks for making this change! In the interest of getting this PR merged today, I've pushed the changes I suggested in my comments.

**Review by jrieken — APPROVED** [review]
