### PR TITLE
Render the overview page with React

### LINKED ISSUE #416: Cannot load avatars from GitHub Enterprise URLs
- Extension version: 0.1.2
- VSCode Version: 1.28.0-insider
- OS: macOS 10.13.6

Steps to Reproduce:

1. Open a Pull Request from a GitHub Enterprise repo
2. Add a PR comment

Screenshot:

image

This is likely because the `user.avatar_url` is used without authentication.

### PR DESCRIPTION
**Pull request by queerviolet**
This PR introduces React, which we then use to render the preview page.

The conversion is fairly straightforward, mostly maintaining the page structure and appearance while converting the plumbing to React. We now use a React context—the `PullRequestContext`, defined in `context.tsx`, to pass mutation functions down to components. The context object, initialized at page load time, also maintains the current state of the PR, and sends it to the root component via an event listener.

Fixes #416

TODO:
  - [X] Render the header and details view
  - [X] Render timeline events:
    - [X] Commit
    - [X] Review
    - [x] Merged
  - [X] Render diffs
  - [X] Comment widget
  - [x] Action bar
  - [X] Wire actions via a pull request context
    - [X] For checking out branches
    - [X] For exiting review mode
    - [X] For submitting comments
    - [x] For editing comments

### CODE REVIEW

File: preview-src/timeline.tsx [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+	<div className='comment-container commit'>
+		<div className='commit-message'>
+			{commitIcon}
+			<div className='avatar-container'>
+				<Avatar for={event.author} />
+			</div>
+			<AuthorLink for={event.author} />
+			<div className='message'>{event.message}</div>
+		</div>
+		<a className='sha' href={event.url}>{event.sha.slice(0, 7)}</a>
```
Comment (RMacfarlane) [inline preview-src/timeline.tsx]: I think this should be `event.htmlUrl` instead of `event.url`. We should get rid of the `url` property on `CommitEvent`

File: src/common/timelineEvent.ts [hunk 2]
```diff
@@ -61,6 +62,7 @@ export interface CommitEvent {
 }
 
 export interface MergedEvent {
+	id: number;
```
Comment (RMacfarlane) [inline src/common/timelineEvent.ts]: There's an existing issue which is preventing id from being passed through - in `parseGraphQLTimelineEvents` in `github/utils.ts`, there are casts on each object pushed to the return array. We should get rid of these casts, because they're breaking type checking there. `id` should be added to those objects

File: preview-src/timeline.tsx [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+import Timestamp from './timestamp';
+import { CommentView } from './comment';
+import Diff from './diff';
+
+export const Timeline = ({ events }: { events: TimelineEvent[] }) =>
+	<>{
+		events.map(event =>
+			// TODO: Maybe make TimelineEvent a tagged union type?
+			isCommitEvent(event)
+				? <CommitEventView key={event.id} {...event} />
```
Comment (RMacfarlane) [inline preview-src/timeline.tsx]: I'm wondering if each of these views should be in its own file, perhaps grouped together in a folder?

File: preview-src/header.tsx [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+import { Avatar, AuthorLink } from './user';
+import { Spaced } from './space';
+import PullRequestContext from './context';
+import { checkIcon } from './icon';
+import Timestamp from './timestamp';
+
+export const Header = ({ state, title, head, base, url, createdAt, author, isCurrentlyCheckedOut }: PullRequest) =>
+<>
+	<div className='overview-title'>
+		<h2>{title}</h2>
```
[the remark this answers is not in the document]
Comment (queerviolet) [reply preview-src/header.tsx]: ooh! Right good catch.

File: preview-src/timeline.tsx (hunk 3 above)
Comment (queerviolet) [reply preview-src/timeline.tsx]: I mean... maybe. It's kindof on the edge for me, because they're pretty small and they're only referenced by the timeline.

We could pull out the thread view? That seems like it could be useful elsewhere at some point, and it's most of the complexity.

File: preview-src/header.tsx [hunk 5]
```diff
@@ -0,0 +1,49 @@
...
+
+import { PullRequest } from './cache';
+import { getStatus } from './pullRequestOverviewRenderer';
+import { Avatar, AuthorLink } from './user';
+import { Spaced } from './space';
+import PullRequestContext from './context';
+import { checkIcon } from './icon';
+import Timestamp from './timestamp';
+
+export const Header = ({ state, title, head, base, url, createdAt, author, isCurrentlyCheckedOut }: PullRequest) =>
```
Comment (rebornix) [inline preview-src/header.tsx]: `isCurrentlyCheckedOut` not used here.

Comment (queerviolet) [reply preview-src/header.tsx]: Fixed.

File: preview-src/timeline.tsx (hunk 1 above)
Comment (queerviolet) [reply preview-src/timeline.tsx]: Fixed.

File: preview-src/header.tsx [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+			</Spaced>
+		</span>
+	</div>
+</>;
+
+const CheckoutButtons = () => {
+	const { pr, exitReviewMode, checkout } = useContext(PullRequestContext);
+	if (pr.isCurrentlyCheckedOut) {
+		return <>
+			<button aria-live='polite' className='checkedOut' disabled>{checkIcon} Checked Out</button>
```
[the remark this answers is not in the document]
Comment (queerviolet) [reply preview-src/header.tsx]: Fixed.

**Comment by queerviolet** [comment]
Okay, PTAL! Added the action bar, reviewers, and labels, and fixed up issues from the prev comments.

File: preview-src/index.css [hunk 7]
```diff
@@ -240,7 +248,7 @@ body .hidden-focusable {
 	overflow: hidden;
 }
 
-button {
+button, input[type=submit] {
```
Comment (RMacfarlane) [inline preview-src/index.css]: submit input should also have the same focus and hover behavior as buttons

File: preview-src/overview.tsx [hunk 8]
```diff
@@ -0,0 +1,31 @@
...
+			<Description {...pr} />
+			<Timeline events={pr.events} />
+			<StatusChecks {...pr} />
+			<AddComment {...pr} />
+		</div>
+	</>;
+
+const Description = (pr: PullRequest) =>
+	<div id='description'>
+		<CommentView {...pr} />
```
[the remark this answers is not in the document]
Comment (queerviolet) [reply preview-src/overview.tsx]: Done.

File: preview-src/comment.tsx [hunk 9]
```diff
@@ -0,0 +1,114 @@
...
+					</div>
+				: null
+		}
+		<div className='review-comment-container'>
+			<div className='review-comment-header'>
+				<Spaced>
+					<Avatar for={user || author} />
+					<AuthorLink for={user || author} />
+					commented
+					<Timestamp href={htmlUrl} date={createdAt} />
```
[the remark this answers is not in the document]
Comment (queerviolet) [reply preview-src/comment.tsx]: Done.

File: preview-src/timeline.tsx [hunk 10]
```diff
@@ -0,0 +1,117 @@
...
+		<div className='review-comment-container'>
+			<div className='review-comment-header'>
+				<Spaced>
+					<Avatar for={event.user} />
+					<AuthorLink for={event.user} />{association(event)}
+					reviewed
+					<Timestamp href={event.htmlUrl} date={event.submittedAt} />
+				</Spaced>
+			</div>
+			<div className='comment-body review-comment-body'>{
```
[the remark this answers is not in the document]
Comment (queerviolet) [reply preview-src/timeline.tsx]: Done

File: preview-src/diff.tsx [hunk 11]
```diff
@@ -0,0 +1,49 @@
+import * as React from 'react';
+
+import { DiffHunk, DiffLine } from '../src/common/diffHunk';
+
+export const Diff = ({ hunks, path, outdated=false }: { hunks: DiffHunk[], outdated: boolean, path: string }) =>
+	<div className='diff'>
+		<div className='diffHeader'>
+			<span className={`diffPath ${outdated ? 'outdated' : ''}`}>{path}</span>
```
[the remark this answers is not in the document]
Comment (queerviolet) [reply preview-src/diff.tsx]: Done

File: preview-src/merge.tsx [hunk 12]
```diff
@@ -0,0 +1,176 @@
...
+import { checkIcon, deleteIcon, pendingIcon } from './icon';
+import { Avatar, } from './user';
+import { nbsp } from './space';
+
+export const StatusChecks = (pr: PullRequest) => {
+	const { state, status, mergeable } = pr;
+	const [showDetails, toggleDetails] = useReducer(show => !show, false);
+
+	return <div id='status-checks'>{
+		state === PullRequestStateEnum.Merged
```
[the remark this answers is not in the document]
Comment (queerviolet) [reply preview-src/merge.tsx]: You can't use statements inside JSX expressions. This desugars to:

```tsx
React.createElement('div', { id: 'status-checks' }, [
  state === PullRequestStateEnum.Merged
    ? ...
])
```

So a statement would be invalid inside.

We could assign it to a temp var in an `if` or `switch`, but that seems more roundabout to me?

File: preview-src/merge.tsx [hunk 13]
```diff
@@ -0,0 +1,176 @@
...
+			? 'Pull request successfully merged'
+			:
+		state === PullRequestStateEnum.Closed
+			? 'This pull request is closed'
+			:
+			<>
+				<div className='status-section'>
```
[the remark this answers is not in the document]
Comment (queerviolet) [reply preview-src/merge.tsx]: Done

File: preview-src/merge.tsx [hunk 14]
```diff
@@ -0,0 +1,176 @@
...
+			: `${numOfType} ${statusAdjective} check`;
+
+		statusPhrases.push(status);
+	}
+
+	return statusPhrases.join(' and ');
+}
+
+const StateIcon = ({ state }: { state: string }) =>
+	state === 'success'
```
[the remark this answers is not in the document]
Comment (queerviolet) [reply preview-src/merge.tsx]: That we can do!

File: preview-src/comment.tsx [hunk 15]
```diff
@@ -0,0 +1,114 @@
...
+				}
+			} />;
+	}
+
+	return <div className='comment-container comment review-comment'
+		onMouseEnter={() => setShowActionBar(true)}
+		onMouseLeave={() => setShowActionBar(false)}
+	>
+		{ ((canEdit || canDelete) && showActionBar)
+				? <div className='action-bar comment-actions'>
```
[the remark this answers is not in the document]
Comment (queerviolet) [reply preview-src/comment.tsx]: Fixed

**Comment by StanleyGoldman** [comment]
Reminder from #1125 
- This and #1125 together fix #416 
- [ ] Needs additional functionality to detect and change the displayed here
https://github.com/Microsoft/vscode-pull-request-github/blob/1fa13ebb1bc50e946c27d55aec12c6ac90add710/preview-src/user.tsx#L5-L8

File: preview-src/header.tsx [hunk 16]
```diff
@@ -0,0 +1,49 @@
...
+import { checkIcon } from './icon';
+import Timestamp from './timestamp';
+
+export const Header = ({ state, title, number, head, base, url, createdAt, author, }: PullRequest) =>
+<>
+	<div className='overview-title'>
+		<h2>{title} (<a href={url}>#{number}</a>)</h2>
+		<div className='button-group'>
+			<CheckoutButtons />
+			<button>Refresh</button>
```
[the remark this answers is not in the document]
Comment (queerviolet) [reply preview-src/header.tsx]: Done.

File: preview-src/sidebar.tsx [hunk 17]
```diff
@@ -0,0 +1,47 @@
...
+			}
+		</div>
+		<div id='labels' className='section'>
+			<div className='section-header'>
+				<div>Labels</div>
+				<button title='Add Labels' onClick={addLabels}>{plusIcon}</button>
+			</div>
+			{
+				labels.map(({ name }) =>
+					<div className='section-item label'>
```
[the remark this answers is not in the document]
Comment (queerviolet) [reply preview-src/sidebar.tsx]: Done

**Comment by queerviolet** [comment]
Okay, PTAL! 

@StanleyGoldman — I made sure I got the DI'd version of your fix for avatars. The fallback appears to work as well :)
@RMacfarlane — Thanks for reviewing! I think I got 'em all!

File: preview-src/comment.tsx [hunk 18]
```diff
@@ -0,0 +1,133 @@
...
+	}, [body]);
+
+	if (inEditMode) {
+		return <EditComment body={body}
+			onCancel={
+				() => setEditMode(false)
+			}
+			onSave={
+				text => {
+					editComment({ comment: comment as Comment, text });
```
Comment (RMacfarlane) [inline preview-src/comment.tsx]: I think we need to handle failure cases here, completely removing all of the comment text in a review comment should show an error message instead of updating the text

Also, let's update both the actual data and the body markdown - right now if I edit the text, change it, and save it, and click edit again, the original body is shown

File: preview-src/header.tsx [hunk 19]
```diff
@@ -0,0 +1,61 @@
...
+import PullRequestContext from './context';
+import { checkIcon } from './icon';
+import Timestamp from './timestamp';
+import { PullRequestStateEnum } from '../src/github/interface';
+
+export function Header({ state, title, number, head, base, url, createdAt, author, }: PullRequest) {
+	const { refresh } = useContext(PullRequestContext);
+	return <>
+		<div className='overview-title'>
+			<h2>{title} (<a href={url}>#{number}</a>)</h2>
```
Comment (RMacfarlane) [inline preview-src/header.tsx]: The title should also be editable

File: src/authentication/githubServer.ts [hunk 20]
```diff
@@ -13,7 +13,8 @@ import { onDidChange as onKeychainDidChange, toCanonical, listHosts } from './ke
 const SCOPES: string = 'read:user user:email repo write:discussion';
 const GHE_OPTIONAL_SCOPES: { [key: string]: boolean } = {'write:discussion': true};
 
-const AUTH_RELAY_SERVER = 'https://vscode-auth.github.com';
+// const AUTH_RELAY_SERVER = 'https://vscode-auth.github.com';
+const AUTH_RELAY_SERVER = 'https://client-auth-staging-14a768b.herokuapp.com';
```
Comment (RMacfarlane) [inline src/authentication/githubServer.ts]: should this be reverted?

**Comment by StanleyGoldman** [comment]
In the old version, if i open a pull request whose checks are not all green the "Check Summary" is defaulted to open. In the react based version the "Check Summary" is defaulted to closed.

**Comment by StanleyGoldman** [comment]
Another difference I'm noticing is in the old version. I'm looking at a pull request I've created.
In the old version, the Comment and Request Changes button are disabled while the comment text is empty. In the new version, the Request Changes and Comment button are enabled while the comment text is empty, when I've added text the Request Changes button becomes disabled.

**Comment by queerviolet** [comment]
Thanks for the review everyone 🙏🏽Turnaround on these changes is taking a second. I discovered another issue with comment drafts that needs resolving, too.

File: preview-src/header.tsx (hunk 19 above)
Comment (queerviolet) [reply preview-src/header.tsx]: Fixed.

File: preview-src/comment.tsx (hunk 18 above)
Comment (queerviolet) [reply preview-src/comment.tsx]: Fixed.

File: src/github/pullRequestManager.ts [hunk 21]
```diff
@@ -750,6 +751,37 @@ export class PullRequestManager {
 		}
 	}
 
+	private async ensureTimelineEventAvatars(githubRepository: GitHubRepository, events: TimelineEvent[]): Promise<void>{
```
[the remark this answers is not in the document]
Comment (queerviolet) [reply src/github/pullRequestManager.ts]: Fixed.

File: preview-src/sidebar.tsx [hunk 22]
```diff
@@ -0,0 +1,67 @@
...
+			{
+				labels.map(label => <Label key={label.name} {...label} />)
+			}
+		</div>
+	</div>;
+}
+
+function Reviewer(reviewState: ReviewState) {
+	const	{ reviewer, state } = reviewState;
+	const [ showDelete, setShowDelete ] = useState(false);
```
[the remark this answers is not in the document]
Comment (queerviolet) [reply preview-src/sidebar.tsx]: Fixed.

**Comment by queerviolet** [comment]
Okay, got through those changes, and finally got us saving and restoring draft comments appropriately. PTAL @RMacfarlane @StanleyGoldman

File: preview-src/comment.tsx [hunk 23]
```diff
@@ -0,0 +1,159 @@
...
+	const [inEditMode, setEditMode] = useState(!!currentDraft);
+	const [showActionBar, setShowActionBar] = useState(false);
+
+	useEffect(() => {
+		if (body !== bodyMd) {
+			setBodyMd(body);
+		}
+	}, [body]);
+
+	if (inEditMode) {
```
Comment (RMacfarlane) [inline preview-src/comment.tsx]: I think we need more logic about where the edit comment component gets rendered.

For comments in a review, it should be inside the comment body so that the header is still visible when editing and there's some padding around it, right now it looks like:
Screen Shot 2019-05-06 at 9 09 02 AM

For review comments, the entire review is being replaced:
review_edit

I think description is the special case where replacing all of it with the editing component makes sense

File: preview-src/comment.tsx [hunk 24]
```diff
@@ -0,0 +1,159 @@
...
+		return <EditComment id={id}
+			body={currentDraft || body}
+			onCancel={
+				() => setEditMode(false)
+			}
+			onSave={
+				async text => {
+					try {
+						await editComment({ comment: comment as Comment, text });
```
Comment (RMacfarlane) [inline preview-src/comment.tsx]: Also for the description, the command is different than a normal comment - `pr.edit-description` instead of `pr.edit-comment`. Title is `pr.edit-title`

File: preview-src/comment.tsx [hunk 25]
```diff
@@ -0,0 +1,159 @@
...
+	useEffect(() => {
+		if (body !== bodyMd) {
+			setBodyMd(body);
+		}
+	}, [body]);
+
+	if (inEditMode) {
+		return <EditComment id={id}
+			body={currentDraft || body}
+			onCancel={
```
Comment (RMacfarlane) [inline preview-src/comment.tsx]: If I start editing something, make some changes, and then click cancel, if I click edit again the text shown is my edited text and not the current text. Do we need to clear the pending comment cache at this point?

Comment (RMacfarlane) [reply preview-src/comment.tsx]: One other issue with pending comments - if you start editing the description on one PR, and then without closing the edit component, switch to another, the edit component is still rendered on that one with the old description

File: preview-src/context.tsx [hunk 26]
```diff
@@ -0,0 +1,171 @@
...
+		this.appendReview(await this.postMessage({ command: 'pr.request-changes', args: body }))
+
+	public approve = async (body: string) =>
+		this.appendReview(await this.postMessage({ command: 'pr.approve', args: body }))
+
+	public submit = async (body: string) =>
+		this.appendReview(await this.postMessage({ command: 'pr.submit', args: body }))
+
+	public removeReviewer = async (review: ReviewState) => {
+		await this.postMessage({ command: 'pr.remove-reviewer', args: review });
```
Comment (RMacfarlane) [inline preview-src/context.tsx]: We only need to send the login, not the whole reviewer object. I get this error `Invalid request.

For 'items', {"reviewer"=>{"avatarUrl"=>"https://avatars3.githubusercontent.com/u/3672607?v=4", "login"=>"RMacfarlane", "url"=>"https://github.com/RMacfarlane"}, "state"=>"REQUESTED"} is not a string.`

File: preview-src/timeline.tsx (hunk 10 above)
[the remark this answers is not in the document]
Comment (RMacfarlane) [reply preview-src/timeline.tsx]: oh, sorry, I forgot to mention this then, but when we display "Request Changes" and "Approve" by the pending review, we remove them from the bottom textarea

Screen Shot 2019-05-06 at 9 26 19 AM

**Comment by StanleyGoldman** [comment]
Two things just noticed, don't want to forget.
- On leaving a comment, timeout remains pending
- On leaving a comment, user avatar does not appear

File: preview-src/context.tsx (hunk 26 above)
Comment (queerviolet) [reply preview-src/context.tsx]: Fixed.

File: preview-src/comment.tsx (hunk 25 above)
Comment (queerviolet) [reply preview-src/comment.tsx]: Fixed.

File: preview-src/comment.tsx (hunk 24 above)
Comment (queerviolet) [reply preview-src/comment.tsx]: Fixed.

File: preview-src/comment.tsx (hunk 23 above)
Comment (queerviolet) [reply preview-src/comment.tsx]: Fixed.

File: preview-src/header.tsx [hunk 27]
```diff
@@ -0,0 +1,106 @@
...
+
+function Title({ title, number, url, canEdit, isCurrentlyCheckedOut }: Partial<PullRequest>) {
+	const [ inEditMode, setEditMode ] = useState(false);
+	const [ showActionBar, setShowActionBar ] = useState(false);
+	const [ currentTitle, setCurrentTitle ] = useState(title);
+	const { setTitle, refresh } = useContext(PullRequestContext);
+	const editableTitle =
+		inEditMode
+			?
+				<form
```
[the remark this answers is not in the document]
Comment (queerviolet) [reply preview-src/header.tsx]: Fixed.

File: preview-src/header.tsx [hunk 28]
```diff
@@ -0,0 +1,106 @@
...
+								setCurrentTitle(txt);
+							} finally {
+								setEditMode(false);
+							}
+						}
+					}
+				>
+				<textarea name='text' defaultValue={currentTitle}></textarea>
+				<div className='form-actions'>
+					<button className='secondary'>Cancel</button>
```
[the remark this answers is not in the document]
Comment (queerviolet) [reply preview-src/header.tsx]: Oops, it needed an `onClick`. Fixed.
