### PR TITLE
Receive GitHub auth tokens with a URI handler rather than a WebSocket

### LINKED ISSUE #533: Error signing in to github.com with Error code 803
- Extension version: 0.1.6
- VSCode Version: 1.27.2
- OS: Linux 4.18.5-arch1-1-ARCH #<span></span>1 SMP PREEMPT Fri Aug 24 12:48:58 UTC 2018 x86_64 GNU/Linux
- Browser: Mozilla Firefox for Arch Linux 61.0.2 (64-bit)

Steps to Reproduce:

1. Install the extension and restart VSCode.
2. Push "Sign in" button in the dialog which says "In order to use the Pull Requests functionality, you need to sign in to github.com".
3. The error page come out with Error code 803 (like the screenshot shown below).

image

### PR DESCRIPTION
**Pull request by queerviolet**
The good news: We'll no longer be opening a websocket to the auth server. This entirely removes the possibility of an IP mismatch. The code is a lot simpler as well, which is a nice bonus.

The bad news: Both the browser and VS Code will ask if you want to open the custom URI scheme. On top of that, the auth server asks you if you want to allow the extension to access GitHub, and then GitHub asks you if VS Code in general can access GitHub. Nobody asks you if GitHub can access GitHub, but it's only a matter of time.

Fixes #533, #462, #541 (probably! We now trigger the browser immediately, so the auth flow should have a fighting chance to get underway, though there's always the possibility that we'll quickly run aground on a different reef).

/cc: @sguthals @shana @RMacfarlane

### CODE REVIEW

**Comment by queerviolet** [comment]
<small>oh god</small>

screen shot 2018-10-03 at 11 49 11 pm

**Comment by queerviolet** [comment]
Okay, this is ready for review. I've pushed the update to the auth server already, so the new flow should work against the production auth server.

File: src/authentication/githubServer.ts [hunk 1]
```diff
@@ -237,27 +119,24 @@ export class GitHubServer {
...
+		const host = this.hostUri.toString()
+		const uri = vscode.Uri.parse(
+			`${AUTH_RELAY_SERVER}/authorize?authServer=${host}&callbackUri=${CALLBACK_URI}&scope=${SCOPES}`
+		);
+		vscode.commands.executeCommand('vscode.open', uri);
+		return new Promise<IHostConfiguration>((resolve, reject) => {
+			const subscription = uriHandler.event(async uri => {
+				if (uri.path !== CALLBACK_PATH) return
+				const rsp = await axios.get(`${AUTH_RELAY_SERVER}/verify?${uri.query}`)
+				if (rsp.status !== 200) return
```
Comment (rebornix) [inline src/authentication/githubServer.ts]: same as below, we may want to dispose subscription properly.

File: src/common/uri.ts [hunk 2]
```diff
@@ -101,3 +101,11 @@ export function toPRUri(uri: Uri, pullRequestModel: IPullRequestModel, commit: s
 		query: JSON.stringify(params)
 	});
 }
+
+class UriEventHandler extends EventEmitter<Uri> implements UriHandler {
+	public handleUri(uri: Uri) {
+		this.fire(uri)
```
Comment (rebornix) [inline src/common/uri.ts]: 👍

File: src/authentication/githubServer.ts [hunk 3]
```diff
@@ -237,27 +119,24 @@ export class GitHubServer {
...
+	public login(): Promise<IHostConfiguration> {
+		const host = this.hostUri.toString()
+		const uri = vscode.Uri.parse(
+			`${AUTH_RELAY_SERVER}/authorize?authServer=${host}&callbackUri=${CALLBACK_URI}&scope=${SCOPES}`
+		);
+		vscode.commands.executeCommand('vscode.open', uri);
+		return new Promise<IHostConfiguration>((resolve, reject) => {
+			const subscription = uriHandler.event(async uri => {
+				if (uri.path !== CALLBACK_PATH) return
+				const rsp = await axios.get(`${AUTH_RELAY_SERVER}/verify?${uri.query}`)
```
Comment (rebornix) [inline src/authentication/githubServer.ts]: `axios.get` can throw exceptions, in which case we want to reject the promise as well.

File: src/common/uri.ts (hunk 2 above)
Comment (queerviolet) [reply src/common/uri.ts]: 😺

File: src/authentication/githubServer.ts (hunk 3 above)
Comment (queerviolet) [reply src/authentication/githubServer.ts]: Done (in the adapter logic).

File: src/authentication/githubServer.ts [hunk 4]
```diff
@@ -237,27 +119,24 @@ export class GitHubServer {
...
+				if (rsp.status !== 200) return
+				const {ts, access_token: token} = rsp.data.token
+				if (Date.now() - ts > MAX_TOKEN_RESPONSE_AGE)
+					return reject(new ResponseExpired)
+				resolve({host, username: 'oauth', token})
+				subscription.dispose()
+			})
```
[the remark this answers is not in the document]
Comment (queerviolet) [reply src/authentication/githubServer.ts]: Oops, there is, my lint was off. Fixed em!

File: src/authentication/githubServer.ts (hunk 1 above)
Comment (queerviolet) [reply src/authentication/githubServer.ts]: how embarassing! let us create a rig that ensure this never happens to anyone ever again.

File: src/authentication/githubServer.ts [hunk 5]
```diff
@@ -237,27 +119,24 @@ export class GitHubServer {
...
+		);
+		vscode.commands.executeCommand('vscode.open', uri);
+		return new Promise<IHostConfiguration>((resolve, reject) => {
+			const subscription = uriHandler.event(async uri => {
+				if (uri.path !== CALLBACK_PATH) return
+				const rsp = await axios.get(`${AUTH_RELAY_SERVER}/verify?${uri.query}`)
+				if (rsp.status !== 200) return
+				const {ts, access_token: token} = rsp.data.token
+				if (Date.now() - ts > MAX_TOKEN_RESPONSE_AGE)
+					return reject(new ResponseExpired)
```
[the remark this answers is not in the document]
Comment (queerviolet) [reply src/authentication/githubServer.ts]: fixed it.

**Comment by queerviolet** [comment]
Fixed up the subscription handling logic by making a thing that handles the event emitter -> promise conversion. Also fixed up the lint errors.

PTAL 😄

File: package.json [hunk 6]
```diff
@@ -297,12 +297,13 @@
   },
   "dependencies": {
     "@octokit/rest": "^15.9.5",
-    "node-emoji": "^1.8.1",
+    "axios": "^0.18.0",
```
Comment (RMacfarlane) [inline package.json]: Let's also update the `ThirdPartyNotices.txt` with this

Comment (rebornix) [reply package.json]: I updated it.

File: src/common/utils.ts [hunk 7]
```diff
@@ -127,4 +127,59 @@ export function formatError(e: any): string {
...
+				reject(error);
+			}
+		})
+	).then(
+		(result: U) => {
+			subscription.dispose();
+			return result;
+		},
+		error => {
+			subscription.dispose();
```
Comment (rebornix) [inline src/common/utils.ts]: Can we have a wrapper of EventEmitter instead of patching it? EventEmitter is shared in the extension host so we may want to keep it untouched.

Comment (queerviolet) [reply src/common/utils.ts]: I thought that might be controversial 😉 

Done!

**Comment by queerviolet** [comment]
Okay, done. PTAL.
