### PR TITLE
Provide "pending" mergeability state, wherein updates are polled.

### LINKED ISSUE #1412: Spurious "This branch has conflicts that must be resolved" warning
- Extension version: 0.12.0
- VSCode Version: 1.39.2
- OS: Debian 4.19.37

Steps to Reproduce:

1. Clone the wpt repo and find https://github.com/web-platform-tests/wpt/pull/19754 in the list of pull requests in VS Code. For me it's under "Created By Me" but for others it may be hard to find.
2.At the bottom of the "Description" view, "This branch has conflicts that must be resolved" will be shown. But there are no conflicts to resolve.

Screenshot:
image

### PR DESCRIPTION
**Pull request by JacksonKearl**
Fixes #1412

### CODE REVIEW

File: preview-src/icon.tsx [hunk 1]
```diff
@@ -12,6 +12,7 @@ export const checkIcon = <Icon src={require('../resources/icons/check.svg')} />;
 export const plusIcon = <Icon src={require('../resources/icons/plus.svg')} />;
 export const deleteIcon = <Icon src={require('../resources/icons/delete.svg')} />;
 export const pendingIcon = <Icon src={require('../resources/icons/dot.svg')} />;
+export const loadingIcon = <Icon src={require('../resources/icons/small_dot.svg')} />;
```
Comment (RMacfarlane) [inline preview-src/icon.tsx]: I think we can tweak the existing `pendingIcon`, it looks like it just has the wrong `viewBox`

Comment (JacksonKearl) [reply preview-src/icon.tsx]: Good point, the smaller icon looks better in the status checks area too.

Comment (JacksonKearl) [reply preview-src/icon.tsx]: Fixed
