### PR TITLE
Validation failed creating an issue

### LINKED ISSUE #1868: Validation failed creating an issue
Testing https://github.com/microsoft/vscode-pull-request-github/issues/1857 I got an issue "validation failed"

I might have messed up, but

 1. I don't know what I messed up
 2. The issue closed before this came up, and the text of the issue is lost; probably we should not close the issue 'file' until it's successfully posted

edit: looks like my sign in might have expired, I noticed in the view I am currently logged out

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #1868

### CODE REVIEW

File: src/common/utils.ts [hunk 1]
```diff
@@ -108,13 +128,20 @@ export function formatError(e: HookError | any): string {
...
 
 	let errorMessage = e.message;
-	const furtherInfo = (e as HookError).errors && (e as HookError).errors!.map((error: any) => {
-		if (typeof error === 'string') {
-			return error;
-		} else {
-			return error.message;
-		}
-	}).join(', ');
+	let furtherInfo: string | undefined
```
Comment (RMacfarlane) [inline src/common/utils.ts:131]: nit: semicolon

File: src/common/utils.ts [hunk 2]
```diff
@@ -108,13 +128,20 @@ export function formatError(e: HookError | any): string {
...
+	if (e.message === 'Validation Failed' && hasFieldErrors(e)) {
+		furtherInfo = e.errors.map(error => {
+			return `Value ${error.value} cannot be set for field ${error.field} (code: ${error.code})`;
```
Comment (RMacfarlane) [inline src/common/utils.ts:134]: I would surround ${error.value} in quotes to make it clear this is a user provided value
