### PR TITLE
Fix extra search API calls when polling for Padawan PR changes

### LINKED ISSUE #7542: Opening a PR description can cause a flurry of GitHub search API calls
The problem occurs in the polling for Padawan PR updates. When you open a PR description, we get a bunch of info about the PR. This in turn causes PR update events to fire, which triggers the check for Padawan PR updates

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #7542

### CODE REVIEW

File: src/github/copilotPrWatcher.ts [hunk 1]
```diff
@@ -139,7 +140,11 @@ export class CopilotPRWatcher extends Disposable {
 	private _initialize() {
 		this._getStateChanges();
 		this._pollForChanges();
-		this._register(this._reposManager.onDidChangeAnyPullRequests(() => this._getStateChanges()));
+		this._register(this._reposManager.onDidChangeAnyPullRequests(e => {
+			if (e.some(pr => COPILOT_ACCOUNTS[pr.model.author.login])) {
+				debounce(this._getStateChanges, 50);
```
Comment (alexr00) [inline src/github/copilotPrWatcher.ts]: When a PR description is opened, we get several PR changed events. Debounce so we don't refrsh the states many times. Only refresh the state changes if one of the changed PRs was Padawan.

**Review by aeschli — APPROVED** [review]
