### PR TITLE
Commit & Create PR failed to push new commit

### LINKED ISSUE #4055: Commit & Create PR failed to push new commit
Repro:

1. Create a new branch
2. Create a commit on it
3. Publish the branch to the remote
5. Create another commit on it but this time use the `Commit & Create Pull Request` option from the SCM view

🐛 A PR will be created but only containing the first commit. I expected the second commit to have been pushed before creating the PR.

cc @lszomoru

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #4055

### CODE REVIEW

File: src/commands.ts [hunk 1]
```diff
@@ -381,6 +381,23 @@ export function registerCommands(
...
+		vscode.commands.registerCommand(
+			'pr.pushAndCreate',
+			async (args?: any | Repository) => {
+				if (isSourceControl(args)) {
+					const reviewManager = await chooseReviewManager(args.rootUri.fsPath);
+					if (reviewManager) {
+						if (args.state.HEAD?.upstream) {
+							await args.push();
+						}
+						reviewManager.createPullRequest();
```
Comment (rzhao271) [inline src/commands.ts:394]: Does this part mean that even if the push fails, the PR might be created?

Comment (alexr00) [reply src/commands.ts:394]: If the push fails there will be an uncaught exception, so the PR will not be created.

**Review by connor4312 — APPROVED** [review]
