### PR TITLE
Copy GitHub Permalink doesn't work for GitHub Managed User (ghe.com)

### LINKED ISSUE #7389: Copy GitHub Permalink doesn't work for GitHub Managed User (ghe.com)
- Extension version: 0.112.0
- VSCode Version: 1.100.2
- OS: Ubuntu 22.04
- Repository Clone Configuration (single repository/fork of an upstream repository): Single repository.
- GitHub Product (GitHub.com/GitHub Enterprise version x.x.x): GitHub Managed User (ghe.com) instance.

Steps to Reproduce:

1. Right click on a line. 
2. Copy GitHub Permalink
3. Link is linked to https://github.com/<organization>/<repository> instead of  https://<enterprise>.ghe.com/<organization>/<repository>

Note!
I have logged in to GitHub Managed User (ghe.com) instance with the extension. 

Executing `git remote -v` shows:
```
origin  <enterprise>@<enterprise>.ghe.com:<organization>/<repository>.git (fetch)
origin  <enterprise>@<enterprise>.ghe.com:<organization>/<repository>.git (push)
```

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #7389

### CODE REVIEW

File: src/issues/util.ts [hunk 1]
```diff
@@ -365,22 +364,9 @@ export function getUpstreamOrigin(upstream: Remote, resultHost: string = 'github
...
-		// upstream's origin by https
-		if (fetchUrl.startsWith('https://') && !fetchUrl.startsWith('https://github.com/')) {
-			const host = new URL(fetchUrl).host;
-			if (host.startsWith(enterpriseUri.authority) || !host.includes('github.com')) {
-				resultHost = enterpriseUri.authority;
-			}
-		}
-		if (fetchUrl.startsWith('ssh://')) {
-			fetchUrl = fetchUrl.substr('ssh://'.length);
-		}
```
Comment (Tyriar) [inline src/issues/util.ts:377]: This seems to remove more than what the PR title implies, are we losing anything important here/is there unwanted risk after testing has happened?

**Comment by Rudedogs** [comment]
Hello how are you? Can you help me out

File: src/issues/util.ts (hunk 1 above)
Comment (alexr00) [reply src/issues/util.ts:377]: The reason that copy permaklink didn't work for ghe.com was because I was not properly handling parsing the git remote when it wasn't `https`. `Protocol`'s logic for parsing git remotes is more complete, and I should hav used `Protocol` here from the start. The change replaces the poor git remote parsing, with the more thorough `Protocol` class's git remote parsine.

I tested this with a github.com remote, a GitHub Enterprise remote, and a ghe.com remote.

**Review by benibenj — APPROVED** [review]
