### PR TITLE
Ensure git extension is activated before getting API

### LINKED ISSUE #2572: "Pull Requests" and "Issues" have been showing "loading..." for hours
- VS Code Version: 1.54.2
- OS Version: 10.0.19042 Build 19042

Steps to Reproduce:

1. Install GitHub Pull Requests and Issues in VSCode
2. Authorize with Github
3. Go to the Github Section with the tab on the left side
4. Pull Requests and Issues have been showing "loading..." for hours

Does this issue occur when all extensions are disabled?: No

### PR DESCRIPTION
**Pull request by RMacfarlane**
Fixes #2572

### CODE REVIEW

File: src/gitProviders/builtinGit.ts [hunk 1]
```diff
@@ -30,17 +30,26 @@ export class BuiltinGitProvider implements IGit, vscode.Disposable {
...
 	private constructor(extension: vscode.Extension<GitExtension>) {
 		const gitExtension = extension.exports;
-		this._gitAPI = gitExtension.getAPI(1);
+
+		try {
+			this._gitAPI = gitExtension.getAPI(1);
+		} catch (e) {
+			// The git extension will throw if a git model cannot be found, i.e. if git is not installed.
+			vscode.window.showErrorMessage('Activating the Pull Requests and Issues extension failed. Please make sure you have git installed.');
+			throw e;
```
Comment (alexr00) [inline src/gitProviders/builtinGit.ts:39]: Is this going to cause a error on web?

**Review by alexr00 — APPROVED** [review]

File: src/gitProviders/builtinGit.ts (hunk 1 above)
Comment (alexr00) [reply src/gitProviders/builtinGit.ts:39]: Looks like probably not because of the if check in `createProvider` below.

Comment (RMacfarlane) [reply src/gitProviders/builtinGit.ts:39]: yeah, I think it should be handled there
