### PR TITLE
Rendering ignoring line breaks

### LINKED ISSUE #3881: Rendering ignoring line breaks
- Extension version: 0.49.2022082209 
- VSCode Version: 1.70.2
- OS: linux

Steps to Reproduce:
Writing a comment with regular linebreaks (no double space at the end) will render wrong in vscode.

image

in github - the linebreak is rendered properly.

image

The actual content looks like this:

image

While the content is not proper markdown (which would require either an empty line or a double-space to render a linebreak) - i think this extension should align it's rendering to how github is rendering content.

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #3881

### CODE REVIEW

File: src/github/prComment.ts [hunk 1]
```diff
@@ -225,6 +235,16 @@ export class GHPRComment implements vscode.Comment {
 		this.timestamp = new Date(comment.createdAt);
 	}
 
+	get body(): vscode.MarkdownString | string {
+		// VS Code's markdown rendering is more correct and will not render single line breaks as
+		// line breaks in markdown. To make the comment look more like github.com, we replace single line breaks with double.
+		return (this.mode === vscode.CommentMode.Editing) ? this.rawBody : new vscode.MarkdownString(this.rawBody.replace(/(?<!\s)(\r\n|\n)(?!\s)/g, '\n\n'));
```
Comment (hediet) [inline src/github/prComment.ts:241]: Why is this a different regex than above?
Does it make sense to extract this into a new function?

**Review by hediet — APPROVED** [review]

File: src/github/prComment.ts (hunk 1 above)
Comment (alexr00) [reply src/github/prComment.ts:241]: Thanks for the reminder! I prefer to do refactors separate from other changes: https://github.com/microsoft/vscode-pull-request-github/pull/3921
