### PR TITLE
Opening a gist repository gives a fetch error

### LINKED ISSUE #2324: Opening a gist repository gives a fetch error
Issue Type: <b>Bug</b>

1) Clone a wiki (adding `.wiki.git` to a main repository URL) or gist repository
2) Open the cloned repository with VS Code with the extension enabled
3) See error: `Fetching pull requests for remote 'origin' failed, please check if the url <URL> is valid.`

Wiki repository:
image

Gist repository:
image

Extension version: 0.22.0
VS Code version: Code - Insiders 1.52.0-insider (bc13785d3dd99b4b0e9da9aed17bb79809a50804, 2020-12-07T14:46:48.305Z)
OS version: Windows_NT x64 10.0.20262
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.69GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/marc/code/refined-github --remote=wsl+Ubuntu --crash-reporter-id b50261c5-4e04-48dd-9f0a-6d441b513f94|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz (4 x 2393)|
|Memory (System)|3.80GB (1.30GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz (4 x 2393)|
|Memory (System)|3.80GB (1.30GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz (4 x 2393)|
|Memory (System)|3.80GB (1.30GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30208929
wsl2promptcf:30219163
vstry914:30230485
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorercf:30219167
openfilemenu:30219168
pythonvsded773:30223139
pythonvspyt600cf:30228412
core-portspanelcf:30233468

```

</details>

### PR DESCRIPTION
**Pull request by burkeholland**
Fixes #2324

### CODE REVIEW

**Comment by mcornella** [comment]
I think the fix would be either to add `gist.github.com = false` to the `_servers` Map, or to look at `host.authority` to see if it's `gist.github.com`. This is a sample value of `host` on a gist repo:
```json
{
	"authority": "gist.github.com",
	"fragment": "",
	"path": "/20dec7376005dec0a1...",
	"query": "",
	"scheme": "https"
}
```

**Comment by mcornella** [comment]
This works for me for both `git@github.com` and `git@gist.github.com`, while keeping functionality for non-gist repos:
```diff
diff --git a/src/authentication/githubServer.ts b/src/authentication/githubServer.ts
index a3859d4..dc87dc0 100644
--- a/src/authentication/githubServer.ts
+++ b/src/authentication/githubServer.ts
@@ -17,6 +17,11 @@ export class GitHubManager {
 			return false;
 		}
 
+		// gist repos are not supported
+		if (host.authority === 'gist.github.com' || /^\/[a-z0-9]+$/i.test(host.path)) {
+			return false;
+		}
+
 		if (this._servers.has(host.authority)) {
 			return !!this._servers.get(host.authority);
 		}
```

File: src/authentication/githubServer.ts [hunk 1]
```diff
@@ -12,8 +12,8 @@ export class GitHubManager {
 			return false;
 		}
 
-		// .wiki repos are not supported
-		if (host.path.endsWith('.wiki')) {
+		// .wiki/.git repos are not supported
+		if (host.path.endsWith('.wiki') || host.path.match(/gist[.]github[.]com/g)) {
```
Comment (alexr00) [inline src/authentication/githubServer.ts:16]: Does this need to be a global regular expression match (`/g`)?

Comment (alexr00) [reply src/authentication/githubServer.ts:16]: I usually go here to visualize regular expressions: https://regexper.com/#%5E%5C%2F%5Ba-z0-9%5D%2B%24

I don't think we want to exclude all github hosts with non-alphanumeric characters in them (I have no idea how often those will occur with enterprise for example). I'm happy with the simple test that this PR uses.

Comment (mcornella) [reply src/authentication/githubServer.ts:16]: I'm ok with ignoring that part and just check the domain name. For that though we need to check `host.authority` instead of `host.path`.

Comment (burkeholland) [reply src/authentication/githubServer.ts]: Removed the `g` for now

Comment (alexr00) [reply src/authentication/githubServer.ts]: @burkeholland, @mcornella is correct, it is `host.authority` then needs to be checked for `gist.github.com`.

**Review by alexr00 — CHANGES_REQUESTED** [review]
Just https://github.com/microsoft/vscode-pull-request-github/pull/2933#discussion_r700247506 then we're good to merge.

**Review by alexr00 — APPROVED** [review]
Ready to merg now!
