### PR TITLE
Hover cards should appear for GH-1783 in addition to #1783

### LINKED ISSUE #1783: Hover cards should appear for GH-1783 in addition to #1783
- Extension version: 0.16.0
- VSCode Version: 1.45.0
- OS: Windows 10 Enterprise

Steps to Reproduce:

1. Hover over a comment like `// see #1783`. A hover card is displayed. This is awesome. :smile_cat:
2. Hover over a comment like `// see GH-1783`. No hover card is displayed. Infinite sadness. :crying_cat_face:

`GH-` references are [supported by GitHub](https://help.github.com/en/github/writing-on-github/autolinked-references-and-urls#issues-and-pull-requests) as a synonym for `#` references. Although `GH-` is less common, we use it in [microsoft/STL](https://github.com/microsoft/STL) comments to avoid ambiguity with Azure DevOps issues.

It appears that supporting `GH-` may be as simple as modifying:
https://github.com/microsoft/vscode-pull-request-github/blob/32c1ca0665b5106b0314a50741a6e2c03ee343bd/src/issues/util.ts#L16-L17

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #1783

### CODE REVIEW

File: src/issues/util.ts [hunk 1]
```diff
@@ -14,8 +14,8 @@ import { StateManager } from './stateManager';
 import { ReviewManager } from '../view/reviewManager';
 import { Repository, GitAPI, Remote, Commit, Ref } from '../typings/git';
 
-export const ISSUE_EXPRESSION = /(([^\s]+)\/([^\s]+))?#([1-9][0-9]*)($|[\s\:\;\-\(\=\)])/;
-export const ISSUE_OR_URL_EXPRESSION = /(https?:\/\/github\.com\/(([^\s]+)\/([^\s]+))\/([^\s]+\/)?(issues|pull)\/([0-9]+)(#issuecomment\-([0-9]+))?)|(([^\s]+)\/([^\s]+))?#([1-9][0-9]*)($|[\s\:\;\-\(\=\)])/;
+export const ISSUE_EXPRESSION = /(([^\s]+)\/([^\s]+))?(#|GH-)([1-9][0-9]*)($|[\s\:\;\-\(\=\)])/;
+export const ISSUE_OR_URL_EXPRESSION = /(https?:\/\/github\.com\/(([^\s]+)\/([^\s]+))\/([^\s]+\/)?(issues|pull)\/([0-9]+)(#issuecomment\-([0-9]+))?)|(([^\s]+)\/([^\s]+))?(#|GH-)([1-9][0-9]*)($|[\s\:\;\-\(\=\)])/;
```
Comment (RMacfarlane) [inline src/issues/util.ts:18]: it would be good to have some unit tests for this
