### PR TITLE
[Nightly] Opening PR description page from tree not working when PR is not checked out

### LINKED ISSUE #2499: [Nightly] Opening PR description page from tree not working when PR is not checked out
Issue Type: <b>Bug</b>

1. Open repo with some PRs, expand a PR node in the tree
2. Click on description node

Nothing happens, the description does not open
Regression from https://github.com/microsoft/vscode-pull-request-github/commit/c8d74ba7985dfb70b1db3a5513c7b7cbf843e061

VS Code version: Code - Insiders 1.54.0-insider (5e74ad5430203eadf89fd8e99695f4ebdb0e62ad, 2021-02-16T10:28:35.712Z)
OS version: Darwin x64 19.6.0

### PR DESCRIPTION
**Pull request by RMacfarlane**
Fixes #2499

### CODE REVIEW

File: src/view/reviewManager.ts [hunk 1]
```diff
@@ -667,7 +668,9 @@ export class ReviewManager {
 			this._createPullRequestHelper = new CreatePullRequestHelper(this.repository);
 			this._createPullRequestHelper.onDidCreate(async createdPR => {
 				await this.updateState();
-				await openDescription(this._context, this._telemetry, createdPR, this._folderRepoManager, this);
+				const treeNodes = await this.changesInPrDataProvider.getChildren();
+				const descriptionNode = treeNodes[0] as DescriptionNode;
```
Comment (alexr00) [inline src/view/reviewManager.ts:672]: To avoid relying on position 0 and casting, you could expose a `getDescriptionNode` on `PullRequestChangesTreeDataProvider`.

**Review by alexr00 — APPROVED** [review]

File: src/view/reviewManager.ts (hunk 1 above)
Comment (RMacfarlane) [reply src/view/reviewManager.ts:672]: Thanks, adding this!
