### PR TITLE
Visual Label not provided for "Title" and "Description" field: A11y_Visual Studio Code Web Extensions_Github Pull request_Create New Request_Labels or Instructions

### LINKED ISSUE #7595: Visual Label not provided for "Title" and "Description" field: A11y_Visual Studio Code Web Extensions_Github Pull request_Create New Request_Labels or Instructions
### GIT Hub Tags:
#A11yTCS; #A11ySev2; #Visual Studio Code Web Extensions; #BM_Visual Studio Code Web Extensions_Web_Aug2025; #DesktopWeb; #A11yMAS; #WCAG3.3.2; #Lables or Instructions; #Win11; #ChromiumEdge; #FTP;

### Environment and OS details:
Application name: Visual Studio Code Web Extensions
ChromiumEdge Version: Version 139.0.3405.86 (Official build) (64-bit)
URL: https://insiders.vscode.dev/github/microsoft/vscode-pull-request-github

### Reproduction Steps:
Open url https://insiders.vscode.dev/github/microsoft/vscode-pull-request-github environment and login with git hub account.
TAB to 'Github Pull request' and press enter.
TAB to Create" button and press enter.
TAB to "Title" and "Description" field.
Observe the issue whether Visual Label is provided for "Title" and "Description" field or not.
### Actual behavior:
Visual Label not provided for "Title" and "Description" field:

### Expected behavior:
The input field should have a clear and descriptive visible label (e.g., "Title" and "Description") to guide users.

### User Impact:
Cognitive disabilities users or those who relying on assistive technologies may not understand the purpose of the field.

### Attachment:

Image

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #7595

### CODE REVIEW

File: webviews/createPullRequestViewNew/app.tsx [hunk 1]
```diff
@@ -220,6 +220,7 @@ export function main() {
 						</div>
 					</div>
 
+					<span className='input-title'>TITLE</span>
```
Comment (Tyriar) [inline webviews/createPullRequestViewNew/app.tsx]: If these are for the inputs you should be using a `<label>` with `id`/`for` attributes to link them. That will also allow clicking the label to focus the input.

Comment (alexr00) [reply webviews/createPullRequestViewNew/app.tsx]: I didn't know about this, thank you!
