### PR TITLE
Pull image urls out of pr comment html

### LINKED ISSUE #6175: Images cannot be displayed in PR comment
- Extension version: v0.94.0
- VSCode Version: 1.92.2 (Universal)
- OS: macOS 14.4 (23E214)

Steps to Reproduce:

1. add a comment with image in PR
QQ_1724835417042

2. go to vscode and check the comment, the image can not be displayed correctly
QQ_1724836020918

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #6175

### CODE REVIEW

File: src/github/prComment.ts [hunk 1]
```diff
@@ -471,3 +482,23 @@ ${lineContents}
...
 }
+
+export function replaceImages(markdownBody: string, htmlBody: string, host: string = 'github.com') {
+	const originalExpression = new RegExp(`https:\/\/${host}\/.+\/assets\/([^\/]+\/)?(?<uuid>${UUID_EXPRESSION.source})`);
+	let originalMatch = markdownBody.match(originalExpression);
+	const htmlHost = host === 'github.com' ? 'githubusercontent.com' : host;
+
+	while (originalMatch) {
+		if (originalMatch.groups?.uuid) {
+			const htmlExpression = new RegExp(`https:\/\/([^"]*${htmlHost})\/[^?]+${originalMatch.groups.uuid}[^"]+`);
```
Comment (mjbvz) [inline src/github/prComment.ts:493]: I think `htmlHost` and maybe the `uuid` needs to be escaped for use in the regular expression. Otherwise `.` will match any char instead of a literal `.`

File: src/github/prComment.ts [hunk 2]
```diff
@@ -364,20 +368,17 @@ ${args[3] ?? ''}
...
 	private async replacePermalink(body: string): Promise<string> {
-		const githubRepositories = this.githubRepositories;
-		if (!githubRepositories || githubRepositories.length === 0) {
+		const githubRepository = this.githubRepository;
+		if (!githubRepository) {
 			return body;
 		}
 
-		const expression = new RegExp(`https://github.com/(.+)/${githubRepositories[0].remote.repositoryName}/blob/([0-9a-f]{40})/(.*)#L([0-9]+)(-L([0-9]+))?`, 'g');
+		const expression = new RegExp(`https://github.com/(.+)/${githubRepository.remote.repositoryName}/blob/([0-9a-f]{40})/(.*)#L([0-9]+)(-L([0-9]+))?`, 'g');
```
Comment (mjbvz) [inline src/github/prComment.ts:376]: Also should be regex escaped just in case

File: src/github/prComment.ts (hunk 1 above)
Comment (alexr00) [reply src/github/prComment.ts]: Thank you for catching these!

**Review by bpasero — APPROVED** [review]
