### PR TITLE
Fix empty files tree

### LINKED ISSUE #3294: After making a change to a PR that was made on a fork the "Files" tree is empty
image

Refreshing the tree doesn't bring the files back.

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #3294

### CODE REVIEW

File: src/view/prChangesTreeDataProvider.ts [hunk 1]
```diff
@@ -73,6 +73,12 @@ export class PullRequestChangesTreeDataProvider extends vscode.Disposable implem
 		reviewModel: ReviewModel,
 		shouldReveal: boolean,
 	) {
+		if (this._pullRequestManagerMap.has(pullRequestManager)) {
+			const existingNode = this._pullRequestManagerMap.get(pullRequestManager);
+			if (existingNode && (existingNode.pullRequestModel === pullRequestModel)) {
+				return;
+			}
+		}
```
Comment (alexr00) [inline src/view/prChangesTreeDataProvider.ts:81]: Previously, the pull request node would get re-added to the tree view, but the old node wouldn't get disposed of. This led to tree nodes that didn't exist in the tree any more trying to refresh themselves, which in turn let to exceptions that prevented the tree from completing it's refresh.

**Review by rebornix — APPROVED** [review]
